Server:
  RunMode: debug
  # RunMode: release
  HttpPort: 9000
  ReadTimeout: 60
  WriteTimeout: 60
General:
  LogSavePath: storage/logs
  LogFileName: log
  LogFileExt: .log
  LogMaxSize: 60
  LogMaxAge: 7
  MaxThreads: 100
  MaxTasks: 100
Database:
  # 树兰安吉医院：espacs:Espacs@2020@tcp(172.16.0.7:3306)/espacs?charset=utf8
  # 杭州树兰医院：espacs:espacs@2017@tcp(10.20.32.212:31967)/espacs?charset=utf8
  DBConn: espacs:Espacs@2020@tcp(172.16.0.7:3306)/espacs?charset=utf8
  # DBConn: hrp:asdf@123@tcp(10.110.20.133:30664)/espacs?charset=utf8  
  DBType: mysql
  MaxIdleConns: 100
  MaxOpenConns: 100
  MaxLifetime: 60
Object:
  # 医院 storageId + resName 可以唯一确定 resId
  OBJECT_ResId: c09fd3b6bdbf420b848e5a9eeca38650
  # 树兰安吉医院AK
  OBJECT_AK: 61237219e4b067be893d71e4
  # 上传：AWS: https://cloud-gateway.rubikstack.com/cloud-file/v1/object
  # 上传：树兰安吉电信云： https://gateway-aj.shulan.com/cloud-file/v1/object
  OBJECT_POST_Upload: http://172.16.0.16:31460/v1/object
  # 下载： AWS: https://cloud-gateway.rubikstack.com/cloud-file/v1/object
  # 下载： 树兰安吉电信云： https://gateway-aj.shulan.com/cloud-file/v1/object
  OBJECT_GET_Download: http://172.16.0.16:31460/v1/object
  # 上传根路径，用来区分每家医院的前缀 hospital_id
  # 安吉医院id:b30717222f104ed6b9525312e79d94a8
  UPLOAD_ROOT: b30717222f104ed6b9525312e79d94a8
  # 数据上传成功更新存储节点
  OBJECT_Upload_Success_Code: 1
  # 设置操作失败补偿次数
  OBJECT_Count: 3
   # 下载存储类型：（0：公有云，1：私有云）
  OBJECT_Store_Type: 0
  # 大文件分段限制
  # 分段依据大小8M
  File_Fragment_Size: 8
  # 增加临时下载地址
  # 接口调用类型：（1.通过S3地址直接下载. 0.通过平台接转发下载）
  OBJECT_Interface_Type: 1
  # 临时下载地址
  OBJECT_Temp_GET_Down: http://cloud-store.shulan.com/v1/object/inquiry
  # 临时上传地址
  OBJECT_Temp_GET_Upload: http://172.16.0.16:31460/v1/object/input

  # 下载接口
  # [GET] http://127.0.0.1/api/v1/Object/Down/AccessNumber/ZMCT123456
  # [GET] http://127.0.0.1/api/v1/Object/Down/UidEnc/ab352356vr322434ser
  # [GET] http://127.0.0.1/api/v1/Object/Down/InstanceKey/654324

  # 上传接口
  # [POST] http://127.0.0.1/api/v1/Object/Upload/AccessNumber/ZMCT123456
  # [POST] http://127.0.0.1/api/v1/Object/Upload/UidEnc/ab352356vr322434ser
  # [POST] http://127.0.0.1/api/v1/Object/Upload/InstanceKey/654324